## Очистка геолокации.
С чем были проблемы:
- координаты, выходящие за пределы Бразилии это явная ошибка, потому что географические названия бразильские
- пустые не заполненные координаты
- выбросы. Они внутри Бразилии, но могут быть за тысячу км, относительно других точек того же города

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd

try:
    # 1. Загрузка данных
    # строки подключения SQLAlchemy
    # db_string = f"postgresql://hakaton_admin:fyT6r5Kd94Nko4d@94.142.142.59:5432/hakaton_test_db"
    db_string = f"postgresql://anketa_admin:f4uh4uhu34fuy34fd@localhost:5432/hakaton2_db"

    engine = create_engine(db_string)
except Exception as e:
    print(f"An error occurred: {e}")

finally:
    # engine.dispose()
    print("Connected.")

Connected.

`Рассказазать как искали координаты по индексу и на google maps`

### Удаление координат, выходящих за пределы Бразилии.
Насколько мы могли, уточнили координаты руками. Если увидим что, что-то обнулилось, разбираемся.

In [2]:
try:
    with engine.connect() as connection:
        connection.execute(text("""
update geolocation_clear set geolocation_lat=null, geolocation_lng=null
WHERE geolocation_lat > 5.27438888
   OR geolocation_lng < -73.98283055
   OR geolocation_lat < -33.75116944
--   OR geolocation_lng > -34.79314722 - там какой-то остров fernandode noronha;
   OR geolocation_lng > -32;
"""))
        connection.commit()
    print("Не корректные координаты удалены.")
except Exception as e:
    print(f"Ошибка при заполнении таблицы: {e}")

Не корректные координаты удалены.

### Определяем радиусы городов

In [5]:
def culc_city_radius():
    global engine
    try:
        with engine.connect() as connection:
            connection.execute(text("""
    -- Добавляем колонку geolocation_radius в analysis_geo_cities, если ее нет.
    ALTER TABLE analysis_geo_cities
    ADD COLUMN IF NOT EXISTS geolocation_radius_km FLOAT;

    -- Обновляем колонку geolocation_radius.
    WITH CityCoordinates AS (
      SELECT
        agc.state_code,
        agc.name AS city_name,  -- Переименовываем name для ясности
        agc.avg_latitude,
        agc.avg_longitude,
        gc.geolocation_lat,
        gc.geolocation_lng,
        -- Вычисляем расстояние между двумя точками на сфере (в градусах широты/долготы).
        -- Используем формулу гаверсинуса для большей точности.
        -- Результат в градусах, нужно будет перевести в км (примерно 111 км на градус).
        COALESCE(DEGREES(ACOS(
          LEAST(1, GREATEST(-1,
            COS(RADIANS(agc.avg_latitude)) * COS(RADIANS(gc.geolocation_lat)) *
            COS(RADIANS(gc.geolocation_lng) - RADIANS(agc.avg_longitude)) +
            SIN(RADIANS(agc.avg_latitude)) * SIN(RADIANS(gc.geolocation_lat))
          ))
        )), 0) AS distance_degrees
      FROM
        analysis_geo_cities agc
      JOIN
        geolocation_clear gc ON agc.state_code = gc.geolocation_state AND agc.name = gc.geolocation_city
    ),
    MaxDistances AS (
      SELECT
        state_code,
        city_name,
    --    distance_degrees
        MAX(distance_degrees) AS max_distance_degrees
      FROM
        CityCoordinates
      GROUP BY
        state_code,
        city_name
    )
    UPDATE analysis_geo_cities
    SET geolocation_radius_km = CASE
      WHEN MaxDistances.max_distance_degrees = 0 THEN 0.1
      ELSE MaxDistances.max_distance_degrees * 111.111 -- Преобразуем градусы в километры (приблизительно)
    END
    FROM MaxDistances
    WHERE analysis_geo_cities.state_code = MaxDistances.state_code AND analysis_geo_cities.name = MaxDistances.city_name;
    """))
            connection.commit()
        print("Близость к центру успешно заполнена.")
    except Exception as e:
        print(f"Ошибка при заполнении таблицы: {e}")

culc_city_radius()

Близость к центру успешно заполнена.

Смотрим что получилось:

In [7]:
import pandas as pd

geo = pd.read_sql_query("""
select state_code, "name", geolocation_radius_km from analysis_geo_cities
where geolocation_radius_km > 50
order by geolocation_radius_km desc;
""", engine)
geo.head(5)

Empty DataFrame
Columns: [state_code, name, geolocation_radius_km]
Index: []

`Такие большие цифры в некоторых городах, говорят о некорректности координат, о выбросах`

- Для каждого города находим медианное значение координат.
- Для каждой координаты расстояние от медианного значения
- Если это расстояние больше 50км, то заменяем координаты на медианные.

In [4]:
try:
    with engine.connect() as connection:
        connection.execute(text("""
-- Добавляем столбцы в analysis_geo_cities, если их еще нет.
ALTER TABLE analysis_geo_cities
ADD COLUMN IF NOT EXISTS median_latitude FLOAT;

ALTER TABLE analysis_geo_cities
ADD COLUMN IF NOT EXISTS median_longitude FLOAT;

-- Заполняем median_latitude и median_longitude.
WITH MedianCoordinates AS (
    SELECT
        gc.geolocation_state AS state_code,
        gc.geolocation_city AS city_name,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY gc.geolocation_lat) AS median_latitude,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY gc.geolocation_lng) AS median_longitude
    FROM
        geolocation_clear gc
    GROUP BY
        gc.geolocation_state, gc.geolocation_city
)
UPDATE analysis_geo_cities
SET median_latitude = mc.median_latitude,
    median_longitude = mc.median_longitude
FROM MedianCoordinates mc
WHERE analysis_geo_cities.state_code = mc.state_code
  AND analysis_geo_cities.name = mc.city_name;

-- Добавляем столбец geolocation_distance_km, если его еще нет.
ALTER TABLE geolocation_clear
ADD COLUMN IF NOT EXISTS geolocation_distance_km FLOAT;

-- Заполняем geolocation_distance_km.
UPDATE geolocation_clear gc
SET geolocation_distance_km = 111.111 * DEGREES(ACOS(
    LEAST(1, GREATEST(-1,
        COS(RADIANS(gc.geolocation_lat)) * COS(RADIANS(agc.median_latitude)) *
        COS(RADIANS(agc.median_longitude) - RADIANS(gc.geolocation_lng)) +
        SIN(RADIANS(gc.geolocation_lat)) * SIN(RADIANS(agc.median_latitude))
    ))
))
FROM analysis_geo_cities agc
WHERE gc.geolocation_state = agc.state_code
  AND gc.geolocation_city = agc.name;

UPDATE geolocation_clear
SET geolocation_lat = agc.median_latitude,
    geolocation_lng = agc.median_longitude
FROM analysis_geo_cities agc
WHERE geolocation_clear.geolocation_state = agc.state_code
  AND geolocation_clear.geolocation_city = agc.name
  AND geolocation_clear.geolocation_distance_km > 50;

"""))
        connection.commit()
    print("Выбросы координат приведены к медиане.")
except Exception as e:
    print(f"Ошибка при заполнении таблицы: {e}")

Выбросы координат приведены к медиане.

### Теперь снова пересчитываем центры городов и штатов
Пересчитываем центры городов и штатов, а так же радиусы городов.

In [8]:
# Пересчёт центров городов
try:
    with engine.connect() as connection:
        connection.execute(text("""
update analysis_geo_cities as agc set 
avg_latitude=gc.avg_latitude,
avg_longitude=gc.avg_longitude
from (
	SELECT DISTINCT geolocation_state AS state_code,
       geolocation_city AS name,
       AVG(geolocation_lat) AS avg_latitude,
       AVG(geolocation_lng) AS avg_longitude
	FROM geolocation_clear gc
	GROUP BY geolocation_state, geolocation_city
) as gc
where agc.state_code =gc.state_code and agc."name" = gc.name;

update analysis_geo_states as ags set 
avg_latitude=gc.avg_latitude,
avg_longitude=gc.avg_longitude
from (
	SELECT DISTINCT geolocation_state AS state_code,
       AVG(geolocation_lat) AS avg_latitude,
       AVG(geolocation_lng) AS avg_longitude
	FROM geolocation_clear gc
	GROUP BY geolocation_state
) as gc
where ags.code =gc.state_code;
"""))
        connection.commit()
    print("Координаты центров городов и штатов успешно обновлены.")
except Exception as e:
    print(f"Ошибка при заполнении таблицы: {e}")

Координаты центров городов и штатов успешно обновлены.

In [9]:
culc_city_radius()
geo = pd.read_sql_query("""
select state_code, "name", geolocation_radius_km from analysis_geo_cities
order by geolocation_radius_km desc;
""", engine)
geo.head(5)

Близость к центру успешно заполнена.

  state_code                  name  geolocation_radius_km
0         go             rio verde              49.814458
1         mt       tangarada serra              49.397859
2         mt               caceres              48.945673
3         mg               curvelo              48.009224
4         sp  campo limpo paulista              47.961439